# Generated by Django 5.1 on 2024-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки главной страницы",
            },
        ),
    ]
