# Generated by Django 5.1 on 2024-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_about_us_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_us",
            name="icon",
            field=models.CharField(
                choices=[
                    ("Сеть", "Сеть"),
                    ("Аналитик", "Аналитик"),
                    ("Развитие", "Развитие"),
                ],
                default=1,
                max_length=155,
                verbose_name="иконка",
            ),
            preserve_default=False,
        ),
    ]
